// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGzdo0KLGQ3YZpPN1h686jj8dKVaHl8vs',
    appId: '1:700263567498:android:eedaa9bc0fae1b1e791d73',
    messagingSenderId: '700263567498',
    projectId: 'pokemon-6a137',
    storageBucket: 'pokemon-6a137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxbQtLnoZrC14ctfWcljQZzTszxy0slps',
    appId: '1:700263567498:ios:41b9317ead36c5e0791d73',
    messagingSenderId: '700263567498',
    projectId: 'pokemon-6a137',
    storageBucket: 'pokemon-6a137.firebasestorage.app',
    androidClientId: '700263567498-3phtfhs977nkg22q0kpnufqmk52b54tl.apps.googleusercontent.com',
    iosClientId: '700263567498-uot5h96ocu72s2qovffn4lkrah65jr2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.cruiseBuddy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHkCQi4cpTjKmogLm0e5Z8s4SJg-qrAU',
    appId: '1:700263567498:web:1484ae0660c30daa791d73',
    messagingSenderId: '700263567498',
    projectId: 'pokemon-6a137',
    authDomain: 'pokemon-6a137.firebaseapp.com',
    storageBucket: 'pokemon-6a137.firebasestorage.app',
    measurementId: 'G-5X17P8XZ49',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxbQtLnoZrC14ctfWcljQZzTszxy0slps',
    appId: '1:700263567498:ios:41b9317ead36c5e0791d73',
    messagingSenderId: '700263567498',
    projectId: 'pokemon-6a137',
    storageBucket: 'pokemon-6a137.firebasestorage.app',
    androidClientId: '700263567498-3phtfhs977nkg22q0kpnufqmk52b54tl.apps.googleusercontent.com',
    iosClientId: '700263567498-uot5h96ocu72s2qovffn4lkrah65jr2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.cruiseBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMHkCQi4cpTjKmogLm0e5Z8s4SJg-qrAU',
    appId: '1:700263567498:web:a4171efe6a9396e0791d73',
    messagingSenderId: '700263567498',
    projectId: 'pokemon-6a137',
    authDomain: 'pokemon-6a137.firebaseapp.com',
    storageBucket: 'pokemon-6a137.firebasestorage.app',
    measurementId: 'G-XJXTPZ3C38',
  );

}